/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nmsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "nmsg.pb-c.h"
void   nmsg__nmsg__init
                     (Nmsg__Nmsg         *message)
{
  static Nmsg__Nmsg init_value = NMSG__NMSG__INIT;
  *message = init_value;
}
size_t nmsg__nmsg__get_packed_size
                     (const Nmsg__Nmsg *message)
{
  assert(message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg__pack
                     (const Nmsg__Nmsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg__pack_to_buffer
                     (const Nmsg__Nmsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Nmsg *
       nmsg__nmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Nmsg *)
     protobuf_c_message_unpack (&nmsg__nmsg__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg__free_unpacked
                     (Nmsg__Nmsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nmsg__nmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nmsg__nmsg_fragment__init
                     (Nmsg__NmsgFragment         *message)
{
  static Nmsg__NmsgFragment init_value = NMSG__NMSG_FRAGMENT__INIT;
  *message = init_value;
}
size_t nmsg__nmsg_fragment__get_packed_size
                     (const Nmsg__NmsgFragment *message)
{
  assert(message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg_fragment__pack
                     (const Nmsg__NmsgFragment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg_fragment__pack_to_buffer
                     (const Nmsg__NmsgFragment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__NmsgFragment *
       nmsg__nmsg_fragment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__NmsgFragment *)
     protobuf_c_message_unpack (&nmsg__nmsg_fragment__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg_fragment__free_unpacked
                     (Nmsg__NmsgFragment *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nmsg__nmsg_payload__init
                     (Nmsg__NmsgPayload         *message)
{
  static Nmsg__NmsgPayload init_value = NMSG__NMSG_PAYLOAD__INIT;
  *message = init_value;
}
size_t nmsg__nmsg_payload__get_packed_size
                     (const Nmsg__NmsgPayload *message)
{
  assert(message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg_payload__pack
                     (const Nmsg__NmsgPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg_payload__pack_to_buffer
                     (const Nmsg__NmsgPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__NmsgPayload *
       nmsg__nmsg_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__NmsgPayload *)
     protobuf_c_message_unpack (&nmsg__nmsg_payload__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg_payload__free_unpacked
                     (Nmsg__NmsgPayload *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__nmsg__field_descriptors[4] =
{
  {
    "payloads",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nmsg__Nmsg, n_payloads),
    offsetof(Nmsg__Nmsg, payloads),
    &nmsg__nmsg_payload__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_crcs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__Nmsg, n_payload_crcs),
    offsetof(Nmsg__Nmsg, payload_crcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__Nmsg, has_sequence),
    offsetof(Nmsg__Nmsg, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Nmsg__Nmsg, has_sequence_id),
    offsetof(Nmsg__Nmsg, sequence_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nmsg__nmsg__field_indices_by_name[] = {
  1,   /* field[1] = payload_crcs */
  0,   /* field[0] = payloads */
  2,   /* field[2] = sequence */
  3,   /* field[3] = sequence_id */
};
static const ProtobufCIntRange nmsg__nmsg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nmsg__nmsg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.Nmsg",
  "Nmsg",
  "Nmsg__Nmsg",
  "nmsg",
  sizeof(Nmsg__Nmsg),
  4,
  nmsg__nmsg__field_descriptors,
  nmsg__nmsg__field_indices_by_name,
  1,  nmsg__nmsg__number_ranges,
  (ProtobufCMessageInit) nmsg__nmsg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nmsg__nmsg_fragment__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgFragment, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgFragment, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgFragment, last),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgFragment, fragment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__NmsgFragment, has_crc),
    offsetof(Nmsg__NmsgFragment, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nmsg__nmsg_fragment__field_indices_by_name[] = {
  4,   /* field[4] = crc */
  1,   /* field[1] = current */
  3,   /* field[3] = fragment */
  0,   /* field[0] = id */
  2,   /* field[2] = last */
};
static const ProtobufCIntRange nmsg__nmsg_fragment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nmsg__nmsg_fragment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.NmsgFragment",
  "NmsgFragment",
  "Nmsg__NmsgFragment",
  "nmsg",
  sizeof(Nmsg__NmsgFragment),
  5,
  nmsg__nmsg_fragment__field_descriptors,
  nmsg__nmsg_fragment__field_indices_by_name,
  1,  nmsg__nmsg_fragment__number_ranges,
  (ProtobufCMessageInit) nmsg__nmsg_fragment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nmsg__nmsg_payload__field_descriptors[8] =
{
  {
    "vid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgPayload, vid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgtype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgPayload, msgtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_sec",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgPayload, time_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_nsec",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Nmsg__NmsgPayload, time_nsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Nmsg__NmsgPayload, has_payload),
    offsetof(Nmsg__NmsgPayload, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__NmsgPayload, has_source),
    offsetof(Nmsg__NmsgPayload, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operator",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__NmsgPayload, has_operator_),
    offsetof(Nmsg__NmsgPayload, operator_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Nmsg__NmsgPayload, has_group),
    offsetof(Nmsg__NmsgPayload, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nmsg__nmsg_payload__field_indices_by_name[] = {
  7,   /* field[7] = group */
  1,   /* field[1] = msgtype */
  6,   /* field[6] = operator */
  4,   /* field[4] = payload */
  5,   /* field[5] = source */
  3,   /* field[3] = time_nsec */
  2,   /* field[2] = time_sec */
  0,   /* field[0] = vid */
};
static const ProtobufCIntRange nmsg__nmsg_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor nmsg__nmsg_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.NmsgPayload",
  "NmsgPayload",
  "Nmsg__NmsgPayload",
  "nmsg",
  sizeof(Nmsg__NmsgPayload),
  8,
  nmsg__nmsg_payload__field_descriptors,
  nmsg__nmsg_payload__field_indices_by_name,
  2,  nmsg__nmsg_payload__number_ranges,
  (ProtobufCMessageInit) nmsg__nmsg_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
