/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Sat Mar  7 13:39:01 2015. */

#ifndef PB_NMSG_PB_H_INCLUDED
#define PB_NMSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _nmsg_Nmsg {
    pb_callback_t payloads;
    pb_callback_t payload_crcs;
    bool has_sequence;
    uint32_t sequence;
    bool has_sequence_id;
    uint64_t sequence_id;
} nmsg_Nmsg;

typedef struct _nmsg_NmsgFragment {
    uint32_t id;
    uint32_t current;
    uint32_t last;
    pb_callback_t fragment;
    bool has_crc;
    uint32_t crc;
} nmsg_NmsgFragment;

typedef struct _nmsg_NmsgPayload {
    uint32_t vid;
    uint32_t msgtype;
    int64_t time_sec;
    uint32_t time_nsec;
    pb_callback_t payload;
    bool has_source;
    uint32_t source;
    bool has_operator;
    uint32_t operator;
    bool has_group;
    uint32_t group;
} nmsg_NmsgPayload;

/* Default values for struct fields */

/* Initializer values for message structs */
#define nmsg_Nmsg_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define nmsg_NmsgFragment_init_default           {0, 0, 0, {{NULL}, NULL}, false, 0}
#define nmsg_NmsgPayload_init_default            {0, 0, 0, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define nmsg_Nmsg_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define nmsg_NmsgFragment_init_zero              {0, 0, 0, {{NULL}, NULL}, false, 0}
#define nmsg_NmsgPayload_init_zero               {0, 0, 0, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define nmsg_Nmsg_payloads_tag                   1
#define nmsg_Nmsg_payload_crcs_tag               2
#define nmsg_Nmsg_sequence_tag                   3
#define nmsg_Nmsg_sequence_id_tag                4
#define nmsg_NmsgFragment_id_tag                 1
#define nmsg_NmsgFragment_current_tag            2
#define nmsg_NmsgFragment_last_tag               3
#define nmsg_NmsgFragment_fragment_tag           4
#define nmsg_NmsgFragment_crc_tag                5
#define nmsg_NmsgPayload_vid_tag                 1
#define nmsg_NmsgPayload_msgtype_tag             2
#define nmsg_NmsgPayload_time_sec_tag            3
#define nmsg_NmsgPayload_time_nsec_tag           4
#define nmsg_NmsgPayload_payload_tag             5
#define nmsg_NmsgPayload_source_tag              7
#define nmsg_NmsgPayload_operator_tag            8
#define nmsg_NmsgPayload_group_tag               9

/* Struct field encoding specification for nanopb */
extern const pb_field_t nmsg_Nmsg_fields[5];
extern const pb_field_t nmsg_NmsgFragment_fields[6];
extern const pb_field_t nmsg_NmsgPayload_fields[9];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
